name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js & Enable Corepack
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Enable Corepack
        run: corepack enable

      - name: Install Yarn 4.x
        run: corepack prepare yarn@4.10.3 --activate

      - name: Install dependencies
        run: yarn install

      - name: Generate database (drizzle-kit)
        run: npx drizzle-kit generate

      - name: Expo prebuild (Android)
        run: npx expo prebuild -p android

      # 新增步骤：全局安装 eas-cli
      - name: Install eas-cli
        run: npm install -g eas-cli

      - name: Build APK with EAS
        run: eas build --platform android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Upload APK with v4
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: dist/*.apk # 按实际产物路径设定
