name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出项目源码
      - name: Checkout source
        uses: actions/checkout@v3

      # 设置 Node 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 安装依赖
      - name: Install dependencies
        run: yarn install

      # 生成数据库
      - name: Generate database (drizzle-kit)
        run: npx drizzle-kit generate

      # Expo 预构建
      - name: Expo prebuild (Android)
        run: npx expo prebuild -p android

      # EAS 云构建 APK
      - name: Build APK with EAS
        run: npx eas build --platform android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # 上传 APK 到 Actions Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: dist/*.apk # 按实际 APK 产物路径设定
